apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: grade-submission-api
  namespace: grade-demo
  labels:
    app: grade-submission
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grade-submission
  template:
    metadata:
      labels:
        app: grade-submission
    spec:
      containers:
        - name: grade-submission-api
          image: nginx:1.28
          ports:
            - containerPort: 3000
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 60s
        - setWeight: 100
